/// ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====> ====>  			Pourc1	Pourc2	Category1						Category2							Category3    			// configure categories in ZombiesCategories.c file
																																													/// (ex: 0.80,	0.95 => 80% chance to spawn zombie in 1st categorie, 15% in 2nd categorie and 5% in 3rd categorie)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_000_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 						// No Zombies (don't modify this one)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_001_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Empty,							Empty,								Empty);							// 1 Outside any dynamic zones
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_010_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 						// 10 
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_020_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Empty,							Empty,								Empty); 						// 20
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_030_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.70,	0.90,	Zombie_Type_BigTown_Slow,		Zombie_Type_BigTown_Weak,			Zombie_Type_BigTown_Strong);	// 30 Big Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_040_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.7,  	0.9,	Zombie_Type_MediumTown_Weak,	Zombie_Type_Industrial_Weak,		Zombie_Type_MediumTown_Strong);	// 40 Medium Town / Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_050_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.8,   1,		Zombie_Type_Industrial_Weak,	Zombie_Type_Industrial_Strong,		Empty); 						// 50 Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_060_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		NBC,							Empty,								Empty); 						// 60 NBC
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_070_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_NorthCountryside,	Empty,								Empty);							// 70 Countyside North
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_071_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.8,  	1,		Zombie_Type_Horde_Weak,			Zombie_Type_Horde_Strong,			Empty); 						// 71 Countyside East
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_072_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.7,  	1,		Zombie_Type_Hunter_Winter,		Zombie_Type_Hunter_Camo,			Empty); 						// 72 Countyside South

ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_101_MilitaryTentesCategories  = new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.95,	1,		Zombie_Type_SmallCamp_Weak,		Zombie_Type_SmallCamp_Strong,		Empty); 						// 101 Military Light
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_102_CastelCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85, 	1,		Zombie_Type_MediumCamp_Weak,	Zombie_Type_MediumCamp_Strong,		Empty); 						// 102 Military Medium
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_103_ChurchCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Priest,				Empty,								Empty); 						// 103 // Church (quantity managed by the json)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_104_ComicoCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85, 	1,		Zombie_Type_BigCamp_Weak,		Zombie_Type_MediumCamp_Strong,		Empty); 						// 104 Military Special Forces
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_105_DispensaryCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.6,  	0.8,	Zombie_Type_BigCamp_Weak,		Zombie_Type_BigCamp_Strong,			Zombie_Type_Scientists); 		// 105 Military + Scientists (Mostly Military)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_106_FireStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.7,	0.8,	Zombie_Type_Scientists,			Zombie_Type_MediumCamp_Strong,		Zombie_Type_BigCamp_Strong);	// 106 Military + Scientists (Mostly Scientists)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_107_FisherCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.8,  	1,		Zombie_Type_Outpost_Civilians,	Zombie_Type_BigCamp_Weak,			Empty);							// 107 Outpost
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_108_GazStationCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85, 	1,		Zombie_Type_Industrial_Weak,	Zombie_Type_Industrial_Strong,		Empty); 						// 108 Industrial
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_109_HolidayCampCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,  	1,		Zombie_Type_Ruins,				Empty,								Empty); 						// 109 Ruins
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_110_HospitalCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.35,	0.70,	Zombie_Type_Hospital_Weak,		Zombie_Type_Hospital_Strong,		Zombie_Type_BigTown_Slow);		// 110 Medical 		(v1.14 update)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_111_IndustrialCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.8,	0.9,	Zombie_Type_FireFighter,		Zombie_Type_NBC_Low,				Zombie_Type_NBC_Hight); 		// 111 Firestation 	(v1.14 update)
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_112_TownHallCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.9,  	1,		Zombie_Type_SmallTown_Weak,		Zombie_Type_SmallTown_Strong,		Empty); 						// 112 Small Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_113_PoliceStationCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.85, 	1,		Zombie_Type_MediumTown_Weak,	Zombie_Type_MediumTown_Strong,		Empty); 						// 113 Medium Town
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_114_PrisonCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.60, 	0.8,	Zombie_Type_BigTown_Slow,		Zombie_Type_Airfield_Weak,			Zombie_Type_Airfield_Strong);	// 114 Airfield
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_115_MilitaryBaseCategories 	= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Zombie_Type_BigTown_Slow,		Empty,								Empty);							// 115 Office Buildings
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_116_RiffyCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,   	1,		Zombie_Type_Isolated,			Empty,								Empty); 						// 116 Isolated
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_117_SchoolCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.8,  	1,		Zombie_Type_School_Weak,		Zombie_Type_School_Strong,			Empty); 						// 117 School
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_118_ShopCategories 			= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		Zombie_Type_Butcher,			Empty,								Empty);	 						// 118 // Shop (quantity managed by the json)

/// Data groups you can tweak to add new configurations					/// Don't worry about variables name, look at the comment at the end of the line instead
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_090_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.6,	1.0,	TEST,							Bloodsucker_Easy,					Empty); 						// Easy Bloodsuckers/NAC
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_091_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.4,	0.9,	Zombie_Type_Scientists,			NAC,								Bloodsucker_Medium); 			// Medium Bloodsuckers
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_092_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.4,	0.9,	Zombie_Type_Scientists,			NAC,								Bloodsucker_Hard); 				// Hard Bloodsuckers
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_093_ZombiesCategories         = new Param5<float, float, TStringArray, TStringArray, TStringArray>    (0.6,	0.9,	Zombie_Type_Scientists,			NAC,								Bloodsucker_Superhard); 		// Superhard Bloodsuckers
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_094_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.4,	0.5,	Empty,							Empty,								Bloodsucker_Superhard); 		// Tunnel Bloodsuckers
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_095_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.6,	0.9,	Zombie_Type_NorthCountryside,	Zombie_Type_Hunters,				Bloodsucker_Hard); 				// Roam Bloodsuckers
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_096_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.4,	0.5,	Empty,							Empty,								Bloodsucker_Hard); 				// Toxic Bloodsucker
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_097_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(1,		1,		NAC,							NAC,								Bloodsucker_Hard); 				// Hard Bloodsucker/NAC
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_098_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(04,	0.5,	NBC,							NBC,								NBC); 							// NBC Zombies
ref autoptr Param5<float, float, TStringArray, TStringArray, TStringArray> data_Horde_099_ZombiesCategories 		= new Param5<float, float, TStringArray, TStringArray, TStringArray>	(0.75,	1,		Zombie_Type_NBC_Low,			Zombie_Type_NBC_Hight,				Empty); 						// 99 Toxic (v1.14 update)

